### PR TITLE
Fix: Was crashing on some devices (NPE during queryIntentServices)

### PR DESCRIPTION
**Pull request by olegcherr**

### CODE REVIEW

**Comment by PaulRashidi** [comment]
Looks good, thanks. Please sign the CLA.

**Comment by olegcherr** [comment]
@PaulRashidi Okay, done ))

**Comment by PaulRashidi** [comment]
You sure you signed it with the same email address associated with the commit? Normally our system auto-updates this thread with a confirmation.

**Comment by olegcherr** [comment]
I signed it!

**Comment by keyboardsurfer** [comment]
I just double checked and it seems like you'll have to sign the "Google" CLA for this project, not the "Android" one.

**Comment by olegcherr** [comment]
I signed it!

**Comment by PaulRashidi** [comment]
Thanks again!

**Pull request merged**
